spring.application.name=demo3

duxweb.api-base-url=https://duxweb.pre-produx.asmtechtn.com
duxweb.stage-api-base-url=https://duxweb.pre-produx.asmtechtn.com
duxweb.trust-all-ssl=true
duxweb.keycloak.auth-base-url=https://duxweb.pre-produx.asmtechtn.com/auth
duxweb.keycloak.realm=DuxWeb
duxweb.keycloak.client-id=asm-apis
duxweb.keycloak.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:WIIWVngUsQgSTyXB50AXm1YyeVtaog7V}
server.port=${PORT:8080}
